### ISSUE TITLE
The write function is not working properly

### ISSUE THREAD

**Issue by iBigDane** [MajicDesigns/MD_PWM#2]
After I call write(255) function of MD_PWM class, I call write(0),the pin is still high.
```
MD_PWM motorPWM = new MD_PWM(Pin);
motorPWM->begin(PWM_FREQ);
motorPWM->write(255);
motorPWM->write(0);
```
I suggest that modify MD_PWM.cpp 118 line, Remove the "else" keyword, I test is ok.

**Comment by MajicDesigns** [comment]
Proposed solution was not correct but close! Fixed and released as v1.1.1
